// app/layout.tsx
import type { Metadata } from "next";
import { Bonheur_Royale, Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import RouteChangeHandler from "@/components/loadingpage/routechange";


const geistSans = Geist({ variable: "--font-geist-sans", subsets: ["latin"] });
const geistMono = Geist_Mono({ variable: "--font-geist-mono", subsets: ["latin"] });
const bonheur = Bonheur_Royale({
  subsets: ["latin"],
  weight: "400",
  variable: "--font-bonheur",
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body
        className={`
          ${geistSans.variable}
          ${geistMono.variable}
          ${bonheur.variable}
          container mx-auto max-w-[2560px] antialiased
        `}
      >
        {/* <-- ini Client Component */}
        <RouteChangeHandler>{children}</RouteChangeHandler>
      </body>
    </html>
  );
}
